on:
  push:
    branches:
      - develop

name: 🚀 Deploy [DEV] POS API on push
jobs:
  web-deploy:
    name: 🎉 Deploy [DEV] POS API
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.emkode.org
          username: emkode@segared.emkode.org
          password: ${{ secrets.ftp_password }}